/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coffee_1Shop;


import Coffee_JavaClasses.DatabaseHelper;
import Coffee_JavaClasses.SendEmail;
import Coffee_JavaClasses.Verification_Code;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
/**
 *
 * @author rieje
 */
public class forgot_password_page extends javax.swing.JFrame {

    /**
     * Creates new form forgot_password_page
     */
    private String enteredEmail;
    private String email;  
    private Connection con;
    public forgot_password_page() {
        initComponents();
   
       
        
        EC.addActionListener(e -> {
            email = EE.getText();
            try {  
                if (DatabaseHelper.isEmailRegistered(email)) {
                    String verification_code = Verification_Code.generateCode();
                    SendEmail.sendVerificationEmail(email, verification_code);              
                    DatabaseHelper.storeVerificationCode(email, verification_code);
               
                    JOptionPane.showMessageDialog(this, "A verification code has been sent to your email.");
                    VC.setVisible(true);
                    CVC.setVisible(true);
                    EE.setEditable(false);
                    EC.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(this, "This email is not registered.");
                } 
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "An error occurred. Please try again later.");  
            }
        });
        
        CVC.addActionListener(e -> {
        String email = EE.getText().trim();
        String enteredCode = VC.getText().trim();
        String storedCode = DatabaseHelper.getVerificationCode(email);
        
        System.out.println("Entered Code: " + enteredCode); 
        System.out.println("Stored Code: " + storedCode);
    });
}
             
    private void clearVerificationCode(String email) {
    try {
        String query = "UPDATE users SET verification_code = NULL WHERE email = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, email);
        ps.executeUpdate();
    } catch (SQLException ex) {
        ex.printStackTrace(); 
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EC = new javax.swing.JButton();
        EE = new javax.swing.JTextField();
        CVC = new javax.swing.JButton();
        VC = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(210, 206, 214));
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Forgot Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Email:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Verification code:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        EC.setText("Confirm");
        EC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECActionPerformed(evt);
            }
        });
        jPanel2.add(EC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        EE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EEActionPerformed(evt);
            }
        });
        jPanel2.add(EE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 319, 25));

        CVC.setText("Verify Code");
        CVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVCActionPerformed(evt);
            }
        });
        jPanel2.add(CVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        VC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VCActionPerformed(evt);
            }
        });
        jPanel2.add(VC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 279, 25));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 146, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coffee_1Shop/Img3forpass.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 620, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VCActionPerformed

    private void CVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVCActionPerformed
        // TODO add your handling code here:
        String enteredCode = VC.getText().trim();
        String storedCode = DatabaseHelper.getVerificationCode(email);

        if (storedCode != null && storedCode.equals(enteredCode)) {
            JOptionPane.showMessageDialog(this, "Verification successful.");

            forgot_pass2_page newPasswordPage = new forgot_pass2_page(email);
            newPasswordPage.setVisible(true); 
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid verification code. Please try again.");
        }
    }//GEN-LAST:event_CVCActionPerformed

    private void EEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EEActionPerformed
        // TODO add your handling code here:
        enteredEmail = EE.getText();
        if (DatabaseHelper.isEmailRegistered(email)) {
            String verification_code = Verification_Code.generateCode();
            SendEmail.sendVerificationEmail(email, verification_code);
            DatabaseHelper.storeVerificationCode(email, verification_code);

            JOptionPane.showMessageDialog(this, "A verification code has been sent to your email.");
            VC.setVisible(true);
            CVC.setVisible(true);
            EE.setEditable(false);
            EC.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Email not found, please check and try again.");
        }
    }//GEN-LAST:event_EEActionPerformed

    private void ECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECActionPerformed
        // TODO add your handling code here:
        email = EE.getText();
    }//GEN-LAST:event_ECActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_password_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_password_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_password_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_password_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_password_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CVC;
    private javax.swing.JButton EC;
    private javax.swing.JTextField EE;
    private javax.swing.JPasswordField VC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
