/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coffee_1Shop;





import Coffee_JavaClasses.DatabaseConnection;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rieje
 */
public class Ordering_page extends javax.swing.JFrame {

    /**
     * Creates new form user_booking_details_page
     */
    public Ordering_page() {
        initComponents();
        
        Qty.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
               updatePrice();
            }           
            public void removeUpdate(DocumentEvent e) {
               updatePrice();
            }
            public void changedUpdate(DocumentEvent e) {
               updatePrice();
            }
            
            private void updatePrice() {    
                try {
                    String select = (String) Coffee.getSelectedItem();
                    int price = 0;
            
                    if (select.equals("Regular Coffee - Large")) {
                        price = 45;
                    } else if (select.equals("Regular Coffee - Small")) {
                        price = 25;
                    } else if (select.equals("Matcha - Large")) {
                        price = 70;
                    } else if (select.equals("Matcha - Small")) {
                        price = 55;
                    }  else if (select.equals("Cappuccino - Large")) {
                        price = 70;
                    }  else if (select.equals("Cappuccino - Small")) {
                        price = 55;
                    }  else if (select.equals("Caramel  - Large")) {
                        price = 65;
                    }  else if (select.equals("Caramel  - Small")) {
                        price = 50;
                    }  else if (select.equals("Mocha  - Large")) {
                        price = 65;
                    }  else if (select.equals("Mocha  - Small")) {
                        price = 50;
                    }  else if (select.equals("French Vanila - Large")) {
                        price = 65;
                    }  else if (select.equals("French Vanila - Small")) {
                        price = 50;
                    }  else if (select.equals("Hazel nut - Large")) {
                        price = 65;
                    }  else if (select.equals("Hazel nut - Small")) {
                        price = 50;
                    }
                
                             
                    int orderValue = Integer.parseInt(Qty.getText());
                    int total = orderValue * price;
                    NumberFormat php = NumberFormat.getCurrencyInstance(new Locale("en", "PH"));
                    String phptotal = php.format(total);
                    if (total % 1 == 0) { 
                        phptotal = phptotal.replaceAll("\\.00$", "");
                        
                    }
                    Pri.setText(phptotal);
                } catch (NumberFormatException ex) {
                    Pri.setText("₱0.00");                    
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Pr = new javax.swing.JLabel();
        Pri = new javax.swing.JTextField();
        OrderName = new javax.swing.JTextField();
        Coffee = new javax.swing.JComboBox<>();
        Qty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Proceed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Price", "₱2,999", "₱9,599", "₱15,600", "₱20,000" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 597));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(75, 59, 91));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255, 125));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Booking");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabel3.setText("Order Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabel11.setText("Coffee:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabel12.setText("Quantity:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        Pr.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        Pr.setText("Price:");
        jPanel2.add(Pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Pri.setEditable(false);
        Pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriActionPerformed(evt);
            }
        });
        jPanel2.add(Pri, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 70, 30));

        OrderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderNameActionPerformed(evt);
            }
        });
        jPanel2.add(OrderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 200, 30));

        Coffee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Coffee - Large", "Regular Coffee - Small", "Matcha - Large", "Matcha - Small", "Cappuccino - Large", "Cappuccino - Small", "Caramel  - Large", "Caramel  - Small", "Mocha  - Large", "Mocha  - Small", "French Vanila - Large", "French Vanila - Small", "Hazel nut - Large", "Hazel nut - Small" }));
        Coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeeActionPerformed(evt);
            }
        });
        jPanel2.add(Coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 30));

        Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyActionPerformed(evt);
            }
        });
        jPanel2.add(Qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 130, 30));

        Proceed.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Proceed.setText("Finish Order!");
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });
        jPanel2.add(Proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 390));

        jTable1.setBackground(new java.awt.Color(255, 255, 255, 125));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Order name", "Cofee", "Quantity", "Price"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 390));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Coffee_1Shop/Img2fororder.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 630));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 800, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtyActionPerformed

    private void PriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriActionPerformed

    private void OrderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderNameActionPerformed

    private void CoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoffeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String name = OrderName.getText();
        String coffee = Coffee.getSelectedItem().toString();
        String qty = Qty.getText();
        String price = Pri.getText();

        if (name.isEmpty() || coffee.equals("Select") || qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        model.addRow(new Object[]{name, coffee, qty, price});

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            Object nameObj = model.getValueAt(i, 0);
            Object coffeeObj = model.getValueAt(i, 1);
            Object qtyObj = model.getValueAt(i, 2);
            Object priceObj = model.getValueAt(i, 3);
            
            

            if (nameObj == null && coffeeObj == null && qtyObj == null && priceObj == null) {
                continue;    
            }
            
            if (nameObj == null || coffeeObj == null || qtyObj == null || priceObj == null) {
                JOptionPane.showMessageDialog(this, "One or more rows have empty fields. Please complete all fields.");
                return;
            }
       
            String name = nameObj.toString();
            String coffee = coffeeObj.toString();
            int quantity = Integer.parseInt(qtyObj.toString());
            
            String priceStr = priceObj.toString().replaceAll("[^\\d.]", "");
            if (priceStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Invalid price value at row " + (i + 1));
                return;
            }
            double price;
            try {
                price = Double.parseDouble(priceStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error parsing price at row " + (i + 1) + ": " + priceObj.toString());
                return;
            }
   
            boolean success = DatabaseConnection.insertOrder(name, coffee, quantity, price);
            if (!success) {
                JOptionPane.showMessageDialog(this, "Failed to insert order: " + name);
            }
        }
        JOptionPane.showMessageDialog(this, "Orders submitted successfully!");
        model.setRowCount(0);
    }//GEN-LAST:event_ProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordering_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordering_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordering_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordering_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordering_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Coffee;
    private javax.swing.JTextField OrderName;
    private javax.swing.JLabel Pr;
    private javax.swing.JTextField Pri;
    private javax.swing.JButton Proceed;
    private javax.swing.JTextField Qty;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
